[project]
name = "step-functions-sandbox-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.44",
    "boto3-stubs[cloudformation,s3,sqs,stepfunctions,sts]>=1.35.44",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
