[project]
name = "step-functions-sandbox"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "awsiotsdk>=1.22.0",
    "boto3-stubs[cloudformation,stepfunctions,iot-data,sts,sqs]>=1.35.24",
    "boto3>=1.35.24",
    "pytest>=8.3.3",
]
