AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  InputTransformerFunctionName:
    Type: String
  DoublerFunctionName:
    Type: String
Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine.asl.yaml
      DefinitionSubstitutions:
        InputTransformerFunctionName: !Ref InputTransformerFunctionName
        DoublerFunctionName: !Ref DoublerFunctionName
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref InputTransformerFunctionName
        - LambdaInvokePolicy:
            FunctionName: !Ref DoublerFunctionName
      Tags:
        DefinitionSubstitutions:InputTransformerFunctionName: !Ref InputTransformerFunctionName
        DefinitionSubstitutions:DoublerFunctionName: !Ref DoublerFunctionName
Outputs:
  StateMachineArn:
    Value: !Ref StateMachine