AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  StateMachineArn:
    Type: String
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AWS::AccountId
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: StateMachineInteraction
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:DescribeStateMachine
                  - states:StartExecution
                Resource: !Ref StateMachineArn
              - Effect: Allow
                Action:
                  - states:DescribeExecution
                  - states:GetExecutionHistory
                Resource: !Sub
                  - "${ExecutionArnPrefix}:*"
                  - ExecutionArnPrefix: !Join
                    - ":execution:"
                    - !Split [":stateMachine:", !Ref StateMachineArn]