AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  MacroNamePrefix:
    Type: String
Resources:
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: !Sub "${MacroNamePrefix}OutOfBandDeploymentSupport"
      Description: Adds resource metadata to support out-of-band deployments
      FunctionName: !Ref Function
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          __CODE_PLACEHOLDER__
      Handler: index.handler
      Role: !GetAtt LambdaFunctionExecutionRole.Arn
      Runtime: python3.12
      Timeout: 5
  LambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
